version: 2
jobs:
  build_main_deb:
    docker:
      - image: foundationdb/foundationdb-build:latest

    steps:
      - checkout

      - run:
          name: get foundationdb sources
          command: |
            git clone https://github.com:apple/foundationdb.git
            cd foundationdb
            git checkout tags/6.1.11
            ls -lah

      - run:
          name: test
          command: |
            ls -lah

workflows:
  version: 2
  build:
    jobs:
      - build_main_deb
