version: 2
jobs:
  build_main_deb:
    docker:
      - image: foundationdb/foundationdb-build:latest

    steps:
      - checkout
#      - run:
#          name: get foundationdb sources
#          command: |
#            git clone https://github.com:apple/foundationdb.git
#            cd foundationdb
#            git checkout tags/6.1.11
#            ls -lah

      - run:
          name: create work dir
          command: |
            mkdir -p work
            cd work

      - run:
          name: configure
          command: scl enable devtoolset-8 python27 rh-python36 rh-ruby24 -- bash -c 'cmake -DINSTALL_LAYOUT=DEB ..'

      - run:
          name: compile
          command: scl enable devtoolset-8 python27 rh-python36 rh-ruby24 -- bash -c 'make'

      - run:
          name: make packages
          command: scl enable devtoolset-8 python27 rh-python36 rh-ruby24 -- bash -c 'cpack'

workflows:
  version: 2
  build:
    jobs:
      - build_main_deb
