version: 2.1
jobs:
  checkout:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout
      - run:
          name: get sources
          command: |
            curl -SLsf "https://api.github.com/repos/apple/foundationdb/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' > version
            git clone https://github.com/apple/foundationdb.git src
            git -C src checkout tags/$(cat version)
      - persist_to_workspace:
          root: .
          paths:
            - src
            - version

  make_packages:
    # machine:
      # image: ubuntu-1604:201903-01
    docker:
      - image: circleci/buildpack-deps

    steps:
      - setup_remote_docker

      - attach_workspace:
          at: /tmp/workspace

      - run:
          name: make packages
          command: |
            ls -lah
            docker-compose -f /tmp/workspace/src/build/docker-compose.yaml run prb-packages

workflows:
  version: 2
  build_packages_and_deploy:
    jobs:
      - checkout
      - make_packages:
          requires:
            - checkout
